### ISSUE TITLE
请教如何节点自动选择

### ISSUE THREAD

**Issue by s2228554** [ewigl/mihomo#3]
我试了这个模块非常流畅，但不会设置节点自动选择，试了虚空的语句，改完完全不显示节点信息，可以列举下完整的设置节点自动选择吗

**Comment by ewigl** [comment]
手动选择（原）：
```yaml
  - name: 美国
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/flags/us.png
    <<: *all-proxies
    filter: "US|🇺🇸|美国|United States"
```

自动选择：
```yaml
  - name: 美国
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/flags/us.png
    # 注释掉手动选择的逻辑
    # <<: *all-proxies
    # 将类型设为自动选择
    type: url-test
    # 包含providers内的所有节点
    include-all-providers: true
    # 筛选器
    filter: "US|🇺🇸|美国|United States"
```

其他地区的修改方法是一样的。
修改完配置文件需要在控制台设置界面重载配置或重启内核生效。
